package com.mjaruijs.fischersplayground.news

enum class NewsType {

    OPPONENT_RESIGNED,
    OPPONENT_OFFERED_DRAW,
    OPPONENT_ACCEPTED_DRAW,
    OPPONENT_DECLINED_DRAW,
    OPPONENT_REQUESTED_UNDO,
    OPPONENT_ACCEPTED_UNDO,
    OPPONENT_REJECTED_UNDO,
    NO_NEWS

}